services:
  - type: static
    name: portfolio-website
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
